# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b901e11871e738cfb1f5a89d7fa62210e6db57f3bd6ff12d673a332d9cdb83371058f5e728fd7ee414f859e0156ba9daaee1e3af7064ce4cb5e2457eeaddd67

test:
  secret_key_base: b1199ecb1662845b30f73a0cc7abbbb3016c2f2350adfb564660d45cd8d88fa507128662c2eda1d5d5c942b68a20d8e4d820f65fec682a7761774ccbc349d37a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
